POST http://localhost:8080/api/locations
Content-Type: application/json

{
  "name": "Washington",
  "lat": 13.121,
  "lon": 12.231
}

###
PUT http://localhost:8080/api/locations/4
Content-Type: application/json

{
  "name": "New Orleans",
  "lat": 13.121,
  "lon": 12.231
}

###
GET http://localhost:8080/api/locations
Accept: application/json

###
